# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Course Work' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Course Work

  target 'Course WorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Course WorkUITests' do
    # Pods for testing
  end
  
  use_frameworks!
  pod 'Kanna', '~> 5.2.2'
  pod 'SwiftyJSON', '~> 4.0'
end
