# Generated by Django 3.2 on 2021-05-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_manga',
            field=models.JSONField(default=dict),
        ),
    ]
